stages:
  - lint
  - build

variables:
  MANIFEST_PATH: "build-aux/dev.geopjr.Archives.Devel.json"
  FLATPAK_MODULE: "archives"
  RUNTIME: "46"

flatpak:
  stage: build
  image: 'quay.io/gnome_infrastructure/gnome-runtime-images:gnome-$RUNTIME'
  tags:
    - flatpak
  variables:
    BUNDLE: "dev.geopjr.Archives.Devel.flatpak"
    APP_ID: "dev.geopjr.Archives"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
  script:
    - >
      xvfb-run -a -s "-screen 0 1024x768x24"
      flatpak-builder --keep-build-dirs --user --disable-rofiles-fuse flatpak_app --repo=repo ${BRANCH:+--default-branch=$BRANCH} ${MANIFEST_PATH}
    - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} ${APP_ID} ${BRANCH}
  artifacts:
    name: 'Flatpak Artifacts'
    expose_as: 'Get Flatpak bundle here'
    when: 'always'
    paths:
      - "${BUNDLE}"
    expire_in: 14 days

lint:
  image: "valalang/lint:latest"
  stage: lint
  script:
    - io.elementary.vala-lint -c vala-lint.conf
